"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";
import { createReport, ReportDetail } from "@/lib/api";
import NavBar from "@/components/NavBar";
import Markdown from "@/components/Markdown";
import AgentPipeline, { type StepStatus } from "@/components/AgentPipeline";
import {
  ArrowRightIcon,
  CheckIcon,
  CopyIcon,
  DownloadIcon,
  MicroscopeIcon,
  PlusIcon,
  SpinnerIcon,
} from "@/components/Icons";

const ALL_WAITING: StepStatus[] = ["waiting", "waiting", "waiting"];

function EmptyReportState() {
  return (
    <div className="flex flex-col items-center justify-center px-6 py-16 text-center">
      <span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-sky-100 to-violet-100 text-violet-600 dark:from-sky-950 dark:to-violet-950 dark:text-violet-400">
        <MicroscopeIcon className="h-8 w-8" />
      </span>
      <h4 className="mt-5 text-base font-semibold text-gray-900 dark:text-gray-50">
        No research report yet
      </h4>
      <p className="mt-1 max-w-xs text-sm text-gray-500 dark:text-gray-400">
        Enter a topic above and click <span className="font-medium">Generate Report</span> to begin.
      </p>
    </div>
  );
}

function RunningReportState({ query }: { query: string }) {
  return (
    <div className="flex flex-col items-center justify-center px-6 py-16 text-center">
      <span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-violet-100 text-violet-600 dark:bg-violet-950 dark:text-violet-400">
        <SpinnerIcon className="h-8 w-8 animate-spin" />
      </span>
      <h4 className="mt-5 text-base font-semibold text-gray-900 dark:text-gray-50">
        Generating your report…
      </h4>
      <p className="mt-1 max-w-sm text-sm text-gray-500 dark:text-gray-400">
        “{query}” — the agents are working. This typically takes 15–45 seconds.
      </p>
    </div>
  );
}

function ResearchQuestions({ questions }: { questions: string[] | null }) {
  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900">
      <h3 className="font-semibold text-gray-900 dark:text-gray-50">Research Questions</h3>
      <p className="mt-0.5 text-sm text-gray-500 dark:text-gray-400">
        Questions generated by Planner Agent
      </p>

      {questions ? (
        <ol className="mt-4 flex flex-col gap-3">
          {questions.map((q, i) => (
            <li
              key={i}
              className="flex gap-3 rounded-xl border border-gray-100 bg-gray-50 p-3 text-sm leading-relaxed text-gray-700 dark:border-gray-800 dark:bg-gray-800/50 dark:text-gray-300"
            >
              <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-violet-100 text-xs font-semibold text-violet-700 dark:bg-violet-950 dark:text-violet-400">
                {i + 1}
              </span>
              <span>{q}</span>
            </li>
          ))}
        </ol>
      ) : (
        <p className="mt-4 text-sm text-gray-400 dark:text-gray-500">
          Waiting for the planner agent…
        </p>
      )}
    </div>
  );
}

export default function HomePage() {
  const [checkingAuth, setCheckingAuth] = useState(true);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [report, setReport] = useState<ReportDetail | null>(null);
  const [statuses, setStatuses] = useState<StepStatus[]>(ALL_WAITING);
  const [copied, setCopied] = useState(false);
  const timers = useRef<ReturnType<typeof setTimeout>[]>([]);
  const router = useRouter();

  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => {
      if (!data.user) {
        router.push("/login");
      } else {
        setCheckingAuth(false);
      }
    });
  }, [router]);

  // Animate the pipeline steps while the request is in flight.
  useEffect(() => {
    timers.current.forEach(clearTimeout);
    timers.current = [];

    if (!loading) return;

    setStatuses(["running", "waiting", "waiting"]);
    timers.current.push(
      setTimeout(() => setStatuses(["done", "running", "waiting"]), 2500),
      setTimeout(() => setStatuses(["done", "done", "running"]), 6000)
    );
  }, [loading]);

  // Final state once the request settles.
  useEffect(() => {
    if (loading) return;
    if (report) setStatuses(["done", "done", "done"]);
    if (error) setStatuses(ALL_WAITING);
  }, [loading, report, error]);

  useEffect(() => () => timers.current.forEach(clearTimeout), []);

  function startNewResearch() {
    setQuery("");
    setLoading(false);
    setError(null);
    setReport(null);
    setStatuses(ALL_WAITING);
    setCopied(false);
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!query.trim() || loading) return;
    setLoading(true);
    setError(null);
    setReport(null);
    setCopied(false);
    try {
      const result = await createReport(query.trim());
      setReport(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  async function copyReport() {
    if (!report) return;
    await navigator.clipboard.writeText(report.result);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  function downloadReport() {
    if (!report) return;
    const blob = new Blob([report.result], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `research-report-${report.id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  if (checkingAuth) return null;

  const showDashboard = loading || report !== null || error !== null;

  return (
    <div className="min-h-screen">
      <NavBar />
      <main className="bg-gray-100 dark:bg-zinc-950">
        {showDashboard ? (
          <div className="mx-auto max-w-6xl px-6 py-8">
            <div className="mb-6 flex items-center justify-between">
              <div>
                <h2 className="text-xl font-bold text-gray-900 dark:text-gray-50">
                  Research Dashboard
                </h2>
                <p className="mt-0.5 text-sm text-gray-500 dark:text-gray-400">
                  {report ? "Your report is ready." : "The agents are working on your question."}
                </p>
              </div>
              <button
                onClick={startNewResearch}
                className="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white px-3.5 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 dark:hover:bg-gray-800 dark:hover:text-gray-50"
              >
                <PlusIcon className="h-4 w-4" />
                New research
              </button>
            </div>

            <div className="grid gap-6 lg:grid-cols-3">
              <div className="flex flex-col gap-6">
                <AgentPipeline statuses={statuses} />
                <ResearchQuestions questions={report ? report.sub_questions : null} />
              </div>

              <div className="lg:col-span-2">
                <div className="flex h-full flex-col rounded-2xl border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900">
                  <div className="flex items-start justify-between gap-3 border-b border-gray-100 p-5 dark:border-gray-800">
                    <div>
                      <h3 className="font-semibold text-gray-900 dark:text-gray-50">
                        Research Report
                      </h3>
                      <p className="mt-0.5 text-sm text-gray-500 dark:text-gray-400">
                        Your generated report will appear here
                      </p>
                    </div>
                    {report && (
                      <div className="flex items-center gap-2">
                        <button
                          onClick={copyReport}
                          aria-label="Copy report"
                          className="flex h-9 w-9 items-center justify-center rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-50 hover:text-gray-900 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
                        >
                          {copied ? (
                            <CheckIcon className="h-4 w-4 text-emerald-500" />
                          ) : (
                            <CopyIcon className="h-4 w-4" />
                          )}
                        </button>
                        <button
                          onClick={downloadReport}
                          aria-label="Download report"
                          className="flex h-9 w-9 items-center justify-center rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-50 hover:text-gray-900 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
                        >
                          <DownloadIcon className="h-4 w-4" />
                        </button>
                      </div>
                    )}
                  </div>

                  <div className="flex-1 overflow-y-auto p-6" style={{ maxHeight: "calc(100vh - 260px)" }}>
                    {report ? (
                      <article>
                        <Markdown>{report.result}</Markdown>
                      </article>
                    ) : error ? (
                      <div className="flex flex-col items-center justify-center px-6 py-16 text-center">
                        <h4 className="text-base font-semibold text-red-600 dark:text-red-400">
                          Something went wrong
                        </h4>
                        <p className="mt-1 max-w-sm text-sm text-gray-500 dark:text-gray-400">
                          {error}. Please try again or start a new research.
                        </p>
                      </div>
                    ) : loading ? (
                      <RunningReportState query={query} />
                    ) : (
                      <EmptyReportState />
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <>
            <section className="mx-auto max-w-3xl px-6 pb-10 pt-16 text-center">
              <span className="inline-flex items-center gap-2 rounded-full bg-violet-100 px-4 py-1.5 text-sm font-medium text-violet-700 dark:bg-violet-950 dark:text-violet-300">
                <span className="h-2 w-2 rounded-full bg-emerald-500" />
                Multi-Agent Research System
              </span>
              <h1 className="mt-6 text-4xl font-extrabold tracking-tight text-gray-900 sm:text-5xl dark:text-gray-50">
                Turn questions into{" "}
                <span className="bg-gradient-to-r from-sky-500 to-violet-600 bg-clip-text text-transparent">
                  structured research.
                </span>
              </h1>
              <p className="mx-auto mt-4 max-w-xl text-lg text-gray-500 dark:text-gray-400">
                Ask a question and let our AI agents plan, research, and generate a comprehensive
                report for you.
              </p>
            </section>

            <section className="mx-auto max-w-4xl px-6 pb-20">
              <form
                onSubmit={handleSubmit}
                className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-900"
              >
                <label
                  htmlFor="research-query"
                  className="block font-semibold text-gray-900 dark:text-gray-50"
                >
                  What would you like to research?
                </label>
                <textarea
                  id="research-query"
                  rows={4}
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
                      e.preventDefault();
                      handleSubmit(e);
                    }
                  }}
                  placeholder="Example: Tradeoffs between LangChain and LangGraph for agent orchestration"
                  className="mt-3 w-full resize-y rounded-xl border border-gray-300 bg-white p-4 text-sm text-gray-900 placeholder:text-gray-400 focus:border-violet-500 focus:outline-none focus:ring-2 focus:ring-violet-200 dark:border-gray-700 dark:bg-gray-950 dark:text-gray-100 dark:placeholder:text-gray-500 dark:focus:border-violet-500 dark:focus:ring-violet-900"
                />
                <div className="mt-4 flex items-center justify-between">
                  <p className="text-xs text-gray-400 dark:text-gray-500">
                    Press Ctrl/Cmd + Enter to submit
                  </p>
                  <button
                    type="submit"
                    disabled={!query.trim() || loading}
                    className="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-violet-700 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    Generate Report
                    <ArrowRightIcon className="h-4 w-4" />
                  </button>
                </div>
              </form>

              <div className="mt-6 grid gap-6 md:grid-cols-2">
                <AgentPipeline statuses={ALL_WAITING} />
                <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900">
                  <h3 className="font-semibold text-gray-900 dark:text-gray-50">Research Report</h3>
                  <p className="mt-0.5 text-sm text-gray-500 dark:text-gray-400">
                    Your generated report will appear here
                  </p>
                  <EmptyReportState />
                </div>
              </div>
            </section>
          </>
        )}
      </main>
    </div>
  );
}
