"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { supabase } from "@/lib/supabaseClient";
import { getReport, ReportDetail } from "@/lib/api";
import NavBar from "@/components/NavBar";
import Markdown from "@/components/Markdown";
import { ArrowLeftIcon } from "@/components/Icons";

export default function ReportPage() {
  const router = useRouter();
  const [report, setReport] = useState<ReportDetail | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const id = new URLSearchParams(window.location.search).get("id");
    if (!id) {
      setError("No report id provided");
      return;
    }
    supabase.auth.getUser().then(async ({ data }) => {
      if (!data.user) {
        router.push("/login");
        return;
      }
      try {
        setReport(await getReport(id));
      } catch (err) {
        setError(err instanceof Error ? err.message : "Something went wrong");
      }
    });
  }, [router]);

  return (
    <div className="min-h-screen">
      <NavBar />
      <main className="bg-gray-100 dark:bg-zinc-950">
        <div className="mx-auto max-w-4xl px-6 py-10">
          <Link
            href="/reports"
            className="inline-flex items-center gap-1.5 text-sm font-medium text-violet-600 hover:text-violet-800 dark:text-violet-400 dark:hover:text-violet-300"
          >
            <ArrowLeftIcon className="h-4 w-4" />
            Back to history
          </Link>

          {error && (
            <p className="mt-6 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-600 dark:bg-red-950/50 dark:text-red-400">
              {error}
            </p>
          )}

          {report && (
            <div className="mt-6">
              <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-50">{report.query}</h1>
              <p className="mt-1 text-xs text-gray-400 dark:text-gray-500">
                {new Date(report.created_at).toLocaleString()}
              </p>

              <div className="mt-6 rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900">
                <h2 className="font-semibold text-gray-900 dark:text-gray-50">Sub-questions</h2>
                <p className="mt-0.5 text-sm text-gray-500 dark:text-gray-400">
                  Questions generated by Planner Agent
                </p>
                <ol className="mt-4 flex flex-col gap-3">
                  {report.sub_questions.map((sq, i) => (
                    <li
                      key={i}
                      className="flex gap-3 rounded-xl border border-gray-100 bg-gray-50 p-3 text-sm leading-relaxed text-gray-700 dark:border-gray-800 dark:bg-gray-800/50 dark:text-gray-300"
                    >
                      <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-violet-100 text-xs font-semibold text-violet-700 dark:bg-violet-950 dark:text-violet-400">
                        {i + 1}
                      </span>
                      <span>{sq}</span>
                    </li>
                  ))}
                </ol>
              </div>

              <div className="mt-6 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-900">
                <article>
                  <Markdown>{report.result}</Markdown>
                </article>
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
